// <auto-generated />
using System;
using Data.MouseApiContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MouseApi.Migrations
{
    [DbContext(typeof(MouseDbContext))]
    [Migration("20241114193542_AddMouseAloneFile")]
    partial class AddMouseAloneFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MouseApi.Models.MouseFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MouseFile");
                });

            modelBuilder.Entity("MouseApi.Models.MouseItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MouseFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MouseFileId");

                    b.ToTable("MouseItems");
                });

            modelBuilder.Entity("MouseApi.Models.MouseItem", b =>
                {
                    b.HasOne("MouseApi.Models.MouseFile", "MouseFile")
                        .WithMany()
                        .HasForeignKey("MouseFileId");

                    b.Navigation("MouseFile");
                });
#pragma warning restore 612, 618
        }
    }
}
